# Generated by Django 4.1.1 on 2022-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contenido_neto', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('Descripción', models.CharField(max_length=200)),
            ],
        ),
    ]
