# Generated by Django 4.1.1 on 2022-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Descripción',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='contenido_neto',
        ),
        migrations.AddField(
            model_name='productos',
            name='contenido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='descripción',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
