# Generated by Django 4.1.1 on 2022-09-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_productos_descripción_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='contenido',
            new_name='contenido_neto',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
